using UnityEditor.Experimental.GraphView;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    [Header("Movement Features")]   //Header, script altïŋ―ndaki girdileri daha dïŋ―zenli tutmak iïŋ―in onlarïŋ― sïŋ―nïŋ―flandïŋ―rmayïŋ― saïŋ―lar.
    [SerializeField] private float accelerationForce; //karaktere hareket etmesi iïŋ―in uygulayacaïŋ―ïŋ―mïŋ―z kuvvetin gïŋ―cïŋ―
    [SerializeField] private float maxSpeed;        //ulaïŋ―abileceïŋ―i azami yatay hïŋ―z
    [SerializeField] private float jumpPower;       //zïŋ―plama kuvveti
    [SerializeField] private float jumpCooldown = 0.25f;    //ïŋ―st ïŋ―ste zïŋ―plamalarïŋ― dizginlemek iïŋ―in sayaïŋ―

    private BoxCollider2D boxCollider;  
    private Rigidbody2D body;
    [SerializeField] private MovementJoystick movementJoystick; //joystick referansïŋ―
    [SerializeField] private AttackJoystick attackJoystick;
    private Animator anim; //Animator bileÅenine eriÅim

    [Header("WallJump")]
    [SerializeField] private float wallJumpX;   //sonradan ekleyeceïŋ―imiz duvar zïŋ―plamasïŋ― iïŋ―in kuvvet girdileri
    [SerializeField] private float wallJumpY;

    [Header("Layers")]
    [SerializeField] private LayerMask groundLayer;     //bazïŋ― katmanlarïŋ― karaktere referans gïŋ―stereceïŋ―iz.
    [SerializeField] private LayerMask wallLayer;

    private float horizontalInput;
    private float verticalInput;
    private float currentAcceleration;          //birtakïŋ―m gerekli deïŋ―iïŋ―kenler
    private float jumpTimer;
    private bool isRunning;     //karakterin yÃžrÃžmekte olup olmadÄąÄÄąnÄą kaydeden bool
    private void Awake()            //referans atamalarïŋ―
    {
        body = GetComponent<Rigidbody2D>();
        boxCollider = GetComponent<BoxCollider2D>();
        anim = GetComponent<Animator>();
    }

    void Update()
    {
        horizontalInput = movementJoystick.Horizontal;      //yatay ve dikey girdiler
        verticalInput = movementJoystick.Vertical;


        anim.SetBool("onGround", onGround());

        isRunning = (onGround() && Mathf.Abs(body.linearVelocity.x) >= 0.2f);
        anim.SetBool("isRunning", isRunning);

        if (jumpTimer > 0f)      //zïŋ―plama sayacïŋ―nïŋ― geri sayma
        {
            jumpTimer -= Time.deltaTime;        //Time.deltaTime ile bir deïŋ―eri gerïŋ―ek zamana baïŋ―lïŋ― olarak deïŋ―iïŋ―tirebiliriz
        }

        if (verticalInput >= 0.6f && jumpTimer <= 0f)       //joystick yeterince yukarïŋ―daysa ve zïŋ―plama mïŋ―saitse zïŋ―plamasïŋ―na izin ver
        {
            Jump();
        }


        if (!onGround() && onWall() && body.linearVelocity.y < 0f)    //karakter duvara yapïŋ―ïŋ―ïŋ―ksa sïŋ―rtïŋ―nmesi iïŋ―in yerïŋ―ekimini azaltïŋ―yoruz
            body.gravityScale = 0.3f;
        else
            body.gravityScale = 2.0f;

        if(Mathf.Abs(horizontalInput) >= 0.2f)
        {
            if (horizontalInput >0)                            //joystickin yïŋ―nïŋ―ne gïŋ―re karakteri ïŋ―evir
                transform.localScale = new Vector3(1, 1, 1);
            else if (horizontalInput <0)
                transform.localScale = new Vector3(-1, 1, 1);
        }
    }

    private void FixedUpdate()
    {
        if (Mathf.Abs(horizontalInput) >= 0.25f)        //joystick iïŋ―in kïŋ―ïŋ―ïŋ―k bir sïŋ―rïŋ―kleme sïŋ―nïŋ―rïŋ―
        {
            currentAcceleration = onGround() ? accelerationForce : (accelerationForce / 2);   //karakter yerde deïŋ―ilse itme kuvveti daha az olsun.
            body.AddForce(new Vector2(horizontalInput * currentAcceleration, 0));       //karaktere yatay girdi yïŋ―nïŋ―ne gïŋ―re bir kuvvet uygula
        }

        //joystick bïŋ―rakïŋ―ldïŋ―ïŋ―ïŋ―nda karakterin hïŋ―zla durmasïŋ―nïŋ― saïŋ―lamak iïŋ―in
        if (Mathf.Abs(body.linearVelocity.x) > 0.1f && Mathf.Abs(horizontalInput) < 0.25f) //girdi yoksa ve hareket halindeyse
            body.AddForce(new Vector2(-body.linearVelocity.x * 20f, 0));              //ters yïŋ―nde bir itme uygula

        //karakter azami hïŋ―zïŋ― yïŋ―rïŋ―yerek aïŋ―amamalïŋ―
        if (Mathf.Abs(body.linearVelocity.x) > maxSpeed)              //eïŋ―er hïŋ―zïŋ― azami hïŋ―zïŋ― geïŋ―iyorsa
            body.linearVelocity = new Vector2(Mathf.Sign(body.linearVelocity.x) * maxSpeed, body.linearVelocity.y); //hïŋ―zïŋ― sïŋ―nïŋ―ra indirmeliyiz
    }

    private void Jump()
    {
        if (onWall() && !onGround()) //duvara yapisiksa ve yerde degilse
        {
            //Duvar Zïŋ―plamasïŋ―
            body.AddForce(new Vector2(-Mathf.Sign(transform.localScale.x) * wallJumpX * 50, wallJumpY * 50));
            anim.SetTrigger("jump");

            //karakterin baktïŋ―ïŋ―ïŋ― yïŋ―nïŋ―n tersine ve yukarïŋ― doïŋ―ru
        }
        else if (onGround())        //yerdeyse
        {
            body.AddForce(new Vector2(0, jumpPower * 50)); //yukari dogru jumpPower kadar kuvvet
            anim.SetTrigger("jump");
        }

        jumpTimer = jumpCooldown;

    }

    private bool onGround()
    {
        RaycastHit2D hit = Physics2D.BoxCast(   //bir ïŋ―ïŋ―ïŋ―n yerine bir kutu ateïŋ―leyerek daha tutarlïŋ― bir kontrol yaparïŋ―z.
            boxCollider.bounds.center,          //atïŋ―lacak kutunun baïŋ―langïŋ―cïŋ―
            boxCollider.bounds.size,            //atïŋ―lacak kutunun boyutu
            0,                                  //atïŋ―lacak kutunun aïŋ―ïŋ―sïŋ―
            Vector2.down,                       //atïŋ―lacak kutunun yïŋ―nïŋ―
            0.1f,                               //atïŋ―lacak kutunun gideceïŋ―i max mesafe
            groundLayer);                       //atïŋ―lacak kutunun aradïŋ―ïŋ―ïŋ― Layer
        return hit.collider != null;            //eïŋ―er bir sonuïŋ― alamazsak false deïŋ―er dïŋ―ner. eïŋ―er alïŋ―rsak true dïŋ―ner.
    }
    private bool onWall()
    {
        RaycastHit2D hit = Physics2D.BoxCast(
            boxCollider.bounds.center, 
            boxCollider.bounds.size, 
            0, 
            new Vector2(transform.localScale.x, 0), //karakterin baktïŋ―ïŋ―ïŋ― yïŋ―ne doïŋ―ru olmalïŋ―
            0.2f, 
            wallLayer);

        return hit.collider != null;
    }
}
